'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');const {validate}=require('../scripts/validate-stores.cjs');
const fixture=()=>JSON.parse(fs.readFileSync(path.join(__dirname,'../site/stores/storescan-lab/catalog.json')));
test('published demo tenant validates but internal economics cannot enter its public schema',()=>{assert.equal(validate(fixture()),true);const d=fixture();d.items[0].internal_margin=123;assert.throws(()=>validate(d),/Unapproved public field/);});
test('duplicate IDs and unsafe media block publication',()=>{const d=fixture();d.items.push(d.items[0]);assert.throws(()=>validate(d),/Duplicate product/);const e=fixture();e.items[0].media[0].url='javascript:alert(1)';assert.throws(()=>validate(e),/Unsafe link/);});
test('changed price cannot reuse a release hash',()=>{const d=fixture();d.items[0].variants[0].price_cents++;assert.throws(()=>validate(d),/Release hash mismatch/);});

// The publication fixture may contain archived products. Explicitly make the positive
// checkout fixture available; the negative assertion below still rejects archived items.
test('configured checkout requires a non-fixture live catalog and a scoped public gateway',()=>{const crypto=require('node:crypto'),{canonical}=require('../scripts/validate-stores.cjs'),d=fixture();d.store.checkout={mode:'TEST',gateway_url:'https://gateway.example.test/v1/'+d.store.slug};assert.throws(()=>validate(d),/checkout gateway/);d.store.mode='LIVE';assert.throws(()=>validate(d),/Invalid listing/);for(const p of d.items){p.demo=false;p.fixture=false;p.availability='AVAILABLE';p.commercial_eligibility='CHECKOUT_VERIFICATION_REQUIRED';p.media=[{url:'https://example.test/product.png',rights:'OWNED',provenance:'Test-only owned media declaration'}];}const {release_hash,...payload}=d;d.release_hash=crypto.createHash('sha256').update(canonical(payload)).digest('hex');assert.equal(validate(d),true);d.items[0].availability='ARCHIVED_NOT_FOR_SALE';assert.throws(()=>validate(d),/Invalid listing/);});
test('customer-service links reject unsafe URLs and never expose private business fields',()=>{const d=fixture();d.store.customer_service={name:'Unit test',support_email:'support@example.test',returns_url:'https://example.test/returns',shipping_url:'https://example.test/shipping',privacy_url:'javascript:alert(1)'};assert.throws(()=>validate(d),/Safe customer policy/);d.store.customer_service.privacy_url='https://example.test/privacy';d.store.customer_service.bank_account='private';assert.throws(()=>validate(d),/Unapproved public field/);});
