'use strict';
const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto');
const canonical=v=>v===null||typeof v!=='object'?JSON.stringify(v):Array.isArray(v)?'['+v.map(canonical).join(',')+']':'{'+Object.keys(v).sort().map(k=>JSON.stringify(k)+':'+canonical(v[k])).join(',')+'}';
function validate(d){const fail=m=>{throw Error(m);},only=(x,keys)=>{if(Object.keys(x).some(k=>!keys.includes(k)))fail('Unapproved public field');};
 only(d,['schema_version','store','items','release_hash']);if(d.schema_version!==2||!['DEMO','LIVE'].includes(d.store.mode))fail('Fixture deployment requires DEMO mode');only(d.store,['slug','brand','niche','audience','positioning','color','categories','currency','mode','domains','return_policy','market','checkout']);if(!/^[a-z0-9-]+$/.test(d.store.slug))fail('Invalid slug');if(d.store.checkout){only(d.store.checkout,['gateway_url','mode']);const u=new URL(d.store.checkout.gateway_url);if(d.store.mode!=='LIVE'||!['TEST','LIVE'].includes(d.store.checkout.mode)||u.protocol!=='https:'||u.username||u.password||u.search||u.hash||u.pathname.replace(/\/$/,'')!=='/v1/'+d.store.slug)fail('Invalid checkout gateway');}if(!Array.isArray(d.items)||d.items.length>100)fail('Catalog limit');const ids=new Set(),skus=new Set();
 for(const p of d.items){only(p,['id','title','description','category','seo_title','specifications','variants','currency','shipping_disclosure','media','demo','fixture','commercial_eligibility','source_urls','availability','featured']);if(p.featured!==undefined&&typeof p.featured!=='boolean')fail('Invalid featured placement');if(p.featured&&p.availability==='ARCHIVED_NOT_FOR_SALE')fail('Archived products cannot be featured');if(p.availability&&!['ARCHIVED_NOT_FOR_SALE','AVAILABLE'].includes(p.availability))fail('Invalid availability');if(ids.has(p.id))fail('Duplicate product');ids.add(p.id);if(p.demo!==(d.store.mode==='DEMO')||(d.store.mode==='LIVE'&&p.fixture)||!['NOT_ACCEPTING_ORDERS','CHECKOUT_VERIFICATION_REQUIRED'].includes(p.commercial_eligibility)||p.commercial_eligibility==='CHECKOUT_VERIFICATION_REQUIRED'&&(!d.store.checkout||p.demo||p.fixture||p.availability==='ARCHIVED_NOT_FOR_SALE')||!p.title||!p.description||!p.shipping_disclosure||!d.store.categories.includes(p.category))fail('Invalid listing');if(p.currency!==d.store.currency)fail('Currency mismatch');if(!p.variants?.length||!p.media?.length)fail('Variants and media required');for(const v of p.variants){only(v,['sku','label','price_cents']);if(skus.has(v.sku)||!Number.isSafeInteger(v.price_cents)||v.price_cents<=0)fail('Invalid variant');skus.add(v.sku);}for(const m of p.media){only(m,['url','rights','provenance']);if(d.store.mode==='LIVE'&&(!m.url||m.rights==='GENERATED_PLACEHOLDER'))fail('Real product media required');if(!m.provenance||!['GENERATED_PLACEHOLDER','LICENSED_SUPPLIER','OWNED'].includes(m.rights))fail('Media rights missing');}for(const link of [...p.source_urls,...p.media.map(m=>m.url).filter(Boolean)]){const u=new URL(link);if(u.protocol!=='https:'||u.username||u.password)fail('Unsafe link');}}
 const {release_hash,...payload}=d;if(crypto.createHash('sha256').update(canonical(payload)).digest('hex')!==release_hash)fail('Release hash mismatch');return true;}
module.exports={validate,canonical};
if(require.main===module){const root=path.join(__dirname,'../site/stores');let n=0;for(const slug of fs.readdirSync(root)){const f=path.join(root,slug,'catalog.json');if(fs.existsSync(f)){validate(JSON.parse(fs.readFileSync(f)));n++;}}console.log('Validated '+n+' tenant catalogs');}
